# Python для анализа данных

## Бот в Telegram

### Сбор статистики по Коронавирусу

*Ян Пиле*

### Есть сайт с информацией о распространении вируса в мире
Я предлагаю достать оттуда информацию в виде Pandas dataframe а затем по запросу пользователя в телеграм выгружать ее

Импортируем requests и запишем адрес сайта со статистикой по COVID в переменную

In [52]:
import requests
from bs4 import BeautifulSoup
url1 = 'https://www.worldometers.info/coronavirus/'

После чего через get-запрос достанем текст страницы со статистикой и распарсим ее с помощью BeautifulSoup

In [53]:
url = 'https://www.worldometers.info/coronavirus/'
website = requests.get(url).text
soup = BeautifulSoup(website, 'lxml')
# soup

In [54]:
len(soup.find_all('table'))

3

In [55]:
soup.find_all('table')[0]

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>58,162,630</td>
<td>+38,573</td>
<td>1,181,662</td>
<td>+620</td>
<td>46,821,583</td>
<td>+24,753</td>
<td>10,159,385</td>
<td>18,129</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>81,225,079</td>
<td>+72,885</td>
<td>1,199,688</td>
<td>+1,011</td>
<td>78,452,374</td>
<td>+106,476</td>
<td>1,573,017</td>
<td>28,759</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>38,796,063</td>
<td>+11,498</td>
<td>1,177,961</td>
<td>+193</td>
<td>36,885,617</td>
<td>+1,767</td>
<td>732,485</td>
<td>12,502</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>70,198,086</td>
<td>+332,044</td>
<td>1,377,299</td>
<td>+3,433</td>
<td>61,835,762</td>
<td>+227,920</td>
<td>6,985,025</td>
<td>17,931</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>8,655,556</td>
<td>+1,558</td>
<td>221,970</td>
<td>+30</td>
<td>8,036,175</td>
<td>+770</td>
<td>397,411</td>
<td>1,920</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>345,803</td>
<td>+1,552</td>
<td>4,074</td>
<td>+7</td>
<td>299,408</td>
<td>+73</td>
<td>42,321</td>
<td>118</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>257,383,938</td>
<td>+458,110</td>
<td>5,162,669</td>
<td>+5,294</td>
<td>232,331,625</td>
<td>+361,759</td>
<td>19,889,644</td>
<td>79,359</td>
<td>33,020</td>
<td>662.3</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">48,552,584</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+30,988</td>
<td style="font-weight: bold; text-align:right;">793,470 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+335</td>
<td style="font-weight: bold; text-align:right">38,432,271</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+18,463</td>
<td style="text-align:right;font-weight:bold;">9,326,843</td>
<td style="font-weight: bold; text-align:right">11,840</td>
<td style="font-weight: bold; text-align:right">145,504</td>
<td style="font-weight: bold; text-align:right">2,378</td>
<td style="font-weight: bold; text-align:right">730,995,148</td>
<td style="font-weight: bold; text-align:right">2,190,668</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">333,685,997</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>7</td><td>421</td><td>0</td>
<td style="font-weight: bold; text-align:right">93</td>
<td style="font-weight: bold; text-align:right">1</td>
<td style="font-weight: bold; text-align:right">27,951</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">34,504,689</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+4,764</td>
<td style="font-weight: bold; text-align:right;">465,349 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">33,909,708</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+11,787</td>
<td style="text-align:right;font-weight:bold;">129,632</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">24,668</td>
<td style="font-weight: bold; text-align:right">333</td>
<td style="font-weight: bold; text-align:right">630,575,279</td>
<td style="font-weight: bold; text-align:right">450,812</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,398,753,940</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>41</td><td>3,006</td><td>2</td>
<td style="font-weight: bold; text-align:right">3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">93</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">22,012,150</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+8,833</td>
<td style="font-weight: bold; text-align:right;">612,587 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+176</td>
<td style="font-weight: bold; text-align:right">21,214,823</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">184,740</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">102,550</td>
<td style="font-weight: bold; text-align:right">2,854</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">297,120</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">214,648,031</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>10</td><td>350</td><td>3</td>
<td style="font-weight: bold; text-align:right">41</td>
<td style="font-weight: bold; text-align:right">0.8</td>
<td style="font-weight: bold; text-align:right">861</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">9,806,034</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+40,941</td>
<td style="font-weight: bold; text-align:right;">143,866 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+150</td>
<td style="font-weight: bold; text-align:right">8,050,466</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+39,181</td>
<td style="text-align:right;font-weight:bold;">1,611,702</td>
<td style="font-weight: bold; text-align:right">923</td>
<td style="font-weight: bold; text-align:right">143,407</td>
<td style="font-weight: bold; text-align:right">2,104</td>
<td style="font-weight: bold; text-align:right">351,529,646</td>
<td style="font-weight: bold; text-align:right">5,140,898</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,379,033</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>7</td><td>475</td><td>0</td>
<td style="font-weight: bold; text-align:right">599</td>
<td style="font-weight: bold; text-align:right">2</td>
<td style="font-weight: bold; text-align:right">23,570</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">9,294,188</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+37,120</td>
<td style="font-weight: bold; text-align:right;">262,843 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+1,254</td>
<td style="font-weight: bold; text-align:right">7,992,426</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+36,172</td>
<td style="text-align:right;font-weight:bold;">1,038,919</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">63,650</td>
<td style="font-weight: bold; text-align:right">1,800</td>
<td style="font-weight: bold; text-align:right">220,000,000</td>
<td style="font-weight: bold; text-align:right">1,506,633</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">146,021,007</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>16</td><td>556</td><td>1</td>
<td style="font-weight: bold; text-align:right">254</td>
<td style="font-weight: bold; text-align:right">9</td>
<td style="font-weight: bold; text-align:right">7,115</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">8,550,377</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+23,347</td>
<td style="font-weight: bold; text-align:right;">74,847 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+201</td>
<td style="font-weight: bold; text-align:right">8,057,657</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+29,163</td>
<td style="text-align:right;font-weight:bold;">417,873</td>
<td style="font-weight: bold; text-align:right">1,405</td>
<td style="font-weight: bold; text-align:right">99,896</td>
<td style="font-weight: bold; text-align:right">874</td>
<td style="font-weight: bold; text-align:right">104,088,822</td>
<td style="font-weight: bold; text-align:right">1,216,089</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,593,087</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>10</td><td>1,144</td><td>1</td>
<td style="font-weight: bold; text-align:right">273</td>
<td style="font-weight: bold; text-align:right">2</td>
<td style="font-weight: bold; text-align:right">4,882</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">7,395,222</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+22,678</td>
<td style="font-weight: bold; text-align:right;">118,446 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+23</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">7,048,454</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+6,279</td>
<td style="text-align:right;font-weight:bold;">228,322</td>
<td style="font-weight: bold; text-align:right">1,049</td>
<td style="font-weight: bold; text-align:right">112,950</td>
<td style="font-weight: bold; text-align:right">1,809</td>
<td style="font-weight: bold; text-align:right">151,204,954</td>
<td style="font-weight: bold; text-align:right">2,309,416</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,473,247</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>9</td><td>553</td><td>0</td>
<td style="font-weight: bold; text-align:right">346</td>
<td style="font-weight: bold; text-align:right">0.4</td>
<td style="font-weight: bold; text-align:right">3,487</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>
<td style="font-weight: bold; text-align:right">6,073,098</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,539</td>
<td style="font-weight: bold; text-align:right;">128,852 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+118</td>
<td style="font-weight: bold; text-align:right">5,771,363</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+11,985</td>
<td style="text-align:right;font-weight:bold;">172,883</td>
<td style="font-weight: bold; text-align:right">3,416</td>
<td style="font-weight: bold; text-align:right">71,049</td>
<td style="font-weight: bold; text-align:right">1,507</td>
<td style="font-weight: bold; text-align:right">37,359,561</td>
<td style="font-weight: bold; text-align:right">437,066</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/iran-population/">85,478,137</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>14</td><td>663</td><td>2</td>
<td style="font-weight: bold; text-align:right">41</td>
<td style="font-weight: bold; text-align:right">1</td>
<td style="font-weight: bold; text-align:right">2,023</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">5,341,332</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+48,245</td>
<td style="font-weight: bold; text-align:right;">99,553 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+154</td>
<td style="font-weight: bold; text-align:right">4,610,300</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+22,100</td>
<td style="text-align:right;font-weight:bold;">631,479</td>
<td style="font-weight: bold; text-align:right">2,828</td>
<td style="font-weight: bold; text-align:right">63,471</td>
<td style="font-weight: bold; text-align:right">1,183</td>
<td style="font-weight: bold; text-align:right">81,975,529</td>
<td style="font-weight: bold; text-align:right">974,109</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">84,154,389</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>16</td><td>845</td><td>1</td>
<td style="font-weight: bold; text-align:right">573</td>
<td style="font-weight: bold; text-align:right">2</td>
<td style="font-weight: bold; text-align:right">7,504</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>
<td style="font-weight: bold; text-align:right">5,313,607</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">116,360 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">5,178,639</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">18,608</td>
<td style="font-weight: bold; text-align:right">560</td>
<td style="font-weight: bold; text-align:right">116,096</td>
<td style="font-weight: bold; text-align:right">2,542</td>
<td style="font-weight: bold; text-align:right">25,854,639</td>
<td style="font-weight: bold; text-align:right">564,895</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/argentina-population/">45,768,937</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>9</td><td>393</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">407</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">5,080,663</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">87,810 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">4,901,074</td>
<td style="font-weight: bold; text-align:right;"></td>

На странице три таблицы: одна отвечает за информацию на сегодняшний день (под номером 0), а вторая - за информацию на вчерашний день. Достанем обе таблицы (они лежат между тегами \<\table\>\)

In [56]:
table = soup.find_all('table')[0]
# table

Разобьем таблицу на строки (они лежат между тегами tr)

In [57]:
rows = table.find_all('tr')
# rows

Сначала достанем заголовки (между тегами th). Для примера достанем заголовок первой колонки.

In [58]:
rows[0].find_all('th')[1].get_text().strip()

'Country,Other'

Теперь мы можем достать содержимое ячеек таблицы (между тегами td). Для примера достанем первую запись первого по счету столбца

In [59]:
rows[1].find_all('td')[1].get_text().strip()

'North America'

Протестируем сборку на примере одной колонки, а потом пробежимся по их списку в цикле

In [60]:
col1 = []

col1.append(rows[0].find_all('th')[1].get_text().strip()) # отдельно добавляем заголовок

for row in rows[1:]: # начинаем со второго ряда таблицы, потому что 0 уже обработали выше
    r = row.find_all('td') # находим все теги td для строки таблицы
    col1.append(r[1].get_text().strip()) # сохраняем данные в наш список

print(col1)

['Country,Other', 'North America', 'Asia', 'South America', 'Europe', 'Africa', 'Oceania', '', 'World', 'USA', 'India', 'Brazil', 'UK', 'Russia', 'Turkey', 'France', 'Iran', 'Germany', 'Argentina', 'Spain', 'Colombia', 'Italy', 'Indonesia', 'Mexico', 'Poland', 'Ukraine', 'South Africa', 'Philippines', 'Malaysia', 'Netherlands', 'Peru', 'Iraq', 'Thailand', 'Czechia', 'Canada', 'Romania', 'Chile', 'Japan', 'Belgium', 'Bangladesh', 'Israel', 'Pakistan', 'Serbia', 'Sweden', 'Portugal', 'Vietnam', 'Austria', 'Hungary', 'Kazakhstan', 'Cuba', 'Morocco', 'Switzerland', 'Jordan', 'Greece', 'Nepal', 'Georgia', 'UAE', 'Tunisia', 'Bulgaria', 'Lebanon', 'Belarus', 'Guatemala', 'Slovakia', 'Azerbaijan', 'Croatia', 'Costa Rica', 'Sri Lanka', 'Saudi Arabia', 'Bolivia', 'Ireland', 'Ecuador', 'Myanmar', 'Panama', 'Paraguay', 'Lithuania', 'Denmark', 'Palestine', 'Venezuela', 'Kuwait', 'S. Korea', 'Dominican Republic', 'Slovenia', 'Uruguay', 'Honduras', 'Mongolia', 'Ethiopia', 'Libya', 'Moldova', 'Egypt', 'Armenia', 'Oman', 'Bahrain', 'Bosnia and Herzegovina', 'Kenya', 'Singapore', 'Latvia', 'Qatar', 'Norway', 'Estonia', 'Nigeria', 'North Macedonia', 'Zambia', 'Algeria', 'Australia', 'Albania', 'Botswana', 'Uzbekistan', 'Kyrgyzstan', 'Finland', 'Afghanistan', 'Montenegro', 'Mozambique', 'Zimbabwe', 'Ghana', 'Cyprus', 'Namibia', 'Uganda', 'Cambodia', 'El Salvador', 'Cameroon', 'Rwanda', 'Jamaica', 'Maldives', 'Luxembourg', 'Senegal', 'Trinidad and Tobago', 'Angola', 'Malawi', 'Ivory Coast', 'Laos', 'DRC', 'Réunion', 'Guadeloupe', 'Fiji', 'Suriname', 'Syria', 'Eswatini', 'French Guiana', 'Martinique', 'Madagascar', 'Sudan', 'French Polynesia', 'Malta', 'Mauritania', 'Cabo Verde', 'Guyana', 'Gabon', 'Papua New Guinea', 'Guinea', 'Belize', 'Tanzania', 'Togo', 'Benin', 'Haiti', 'Barbados', 'Somalia', 'Seychelles', 'Bahamas', 'Lesotho', 'Mayotte', 'Burundi', 'Timor-Leste', 'Mauritius', 'Congo', 'Curaçao', 'Tajikistan', 'Nicaragua', 'Mali', 'Taiwan', 'Iceland', 'Aruba', 'Andorra', 'Channel Islands', 'Burkina Faso', 'Brunei', 'Equatorial Guinea', 'Djibouti', 'Saint Lucia', 'South Sudan', 'Hong Kong', 'New Caledonia', 'CAR', 'Isle of Man', 'Gambia', 'Yemen', 'New Zealand', 'Eritrea', 'Gibraltar', 'Niger', 'Guinea-Bissau', 'Sierra Leone', 'Grenada', 'Liberia', 'Bermuda', 'San Marino', 'Dominica', 'Cayman Islands', 'St. Vincent Grenadines', 'Chad', 'Sint Maarten', 'Comoros', 'Antigua and Barbuda', 'Liechtenstein', 'Saint Martin', 'Sao Tome and Principe', 'Monaco', 'Faeroe Islands', 'Turks and Caicos', 'Saint Kitts and Nevis', 'British Virgin Islands', 'Caribbean Netherlands', 'Bhutan', 'St. Barth', 'Anguilla', 'Greenland', 'Diamond Princess', 'Wallis and Futuna', 'Macao', 'Falkland Islands', 'Montserrat', 'Saint Pierre Miquelon', 'Vatican City', 'Solomon Islands', 'Western Sahara', 'MS Zaandam', 'Palau', 'Vanuatu', 'Marshall Islands', 'Samoa', 'Saint Helena', 'Micronesia', 'Tonga', 'China', 'Total:', 'Total:', 'Total:', 'Total:', 'Total:', 'Total:', 'Total:', 'Total:']

In [61]:
col1[:232][-1]

'Tonga'

Чтобы еще раз проверить, запустим для другой колонки - TotalCases

In [13]:
col2 = []

col2.append(rows[0].find_all('th')[2].get_text().strip()) # отдельно добавляем заголовок

for row in rows[1:]: # начинаем со второго ряда таблицы, потому что 0 уже обработали выше
    r = row.find_all('td') # находим все теги td для строки таблицы
    col2.append(r[2].get_text().strip()) # сохраняем данные в наш список

print(col2)

['TotalCases', '55,983,218', '79,027,071', '38,343,935', '63,757,099', '8,558,376', '304,314', '721', '245,974,734', '46,597,003', '34,231,809', '21,766,168', '8,897,149', '8,392,697', '7,936,007', '7,140,294', '5,899,509', '5,284,485', '5,006,675', '4,995,694', '4,752,368', '4,527,120', '4,242,532', '3,793,783', '2,998,891', '2,920,581', '2,851,804', '2,772,491', '2,448,372', '2,198,038', '2,108,549', '2,052,123', '1,884,973', '1,747,701', '1,717,709', '1,706,884', '1,686,318', '1,616,027', '1,568,857', '1,342,718', '1,325,496', '1,271,027', '1,170,422', '1,125,602', '1,087,245', '948,847', '945,201', '934,387', '905,477', '870,834', '859,378', '856,450', '813,334', '811,407', '739,654', '728,210', '712,139', '707,290', '639,332', '597,768', '594,203', '587,765', '558,654', '548,474', '538,320', '524,788', '515,859', '511,854', '496,901', '472,057', '470,008', '460,894', '458,090', '435,526', '422,641', '412,594', '403,318', '399,532', '392,879', '382,796', '378,234', '375,009', '363,712', '358,412', '356,086', '355,129', '332,625', '328,729', '327,286', '304,241', '302,450', '276,685', '253,018', '252,083', '238,845', '211,702', '211,496', '209,672', '206,069', '204,146', '200,856', '188,522', '185,985', '184,905', '184,419', '183,282', '180,989', '165,904', '156,959', '156,166', '151,253', '142,807', '132,808', '130,041', '128,868', '125,920', '122,186', '118,220', '113,422', '102,499', '99,514', '88,530', '87,359', '81,363', '73,904', '64,126', '61,774', '61,252', '57,470', '56,160', '54,668', '54,537', '52,079', '48,670', '46,393', '44,438', '42,898', '42,634', '42,351', '40,238', '40,178', '38,281', '38,169', '37,610', '37,094', '35,252', '35,252', '30,653', '28,823', '26,426', '26,154', '26,024', '24,749', '23,773', '22,259', '22,086', '21,600', '21,269', '20,497', '19,988', '19,785', '17,416', '17,086', '17,047', '16,868', '16,424', '16,422', '16,394', '15,924', '15,865', '15,462', '14,793', '13,461', '13,413', '13,236', '12,905', '12,823', '12,486', '12,338', '12,327', '11,518', '10,848', '9,963', '9,751', '9,417', '6,800', '6,396', '6,300', '6,133', '5,995', '5,943', '5,830', '5,812', '5,637', '5,509', '5,067', '4,905', '4,691', '4,486', '4,239', '4,036', '3,850', '3,705', '3,551', '3,404', '2,974', '2,725', '2,657', '2,621', '2,407', '1,846', '1,589', '1,496', '859', '779', '712', '445', '77', '68', '41', '32', '27', '20', '10', '9', '8', '6', '4', '3', '2', '1', '96,938', '55,983,218', '79,027,071', '38,343,935', '63,757,099', '8,558,376', '304,314', '721', '245,974,734']

А теперь пройдемся циклом по 9 колонкам, сгружая данные в список списков

In [14]:
field_list = []
for i in range(9):
    col = []
    col.append(rows[0].find_all('th')[i+1].get_text().strip()) # отдельно добавляем заголовок
    for row in rows[1:]: # начинаем со второго ряда таблицы, потому что 0 уже обработали выше
        r = row.find_all('td') # находим все теги td для строки таблицы
        col.append(r[i+1].get_text().strip()) # сохраняем данные в наш список
    field_list.append(col)

А вот заголовок второго столбца

In [15]:
field_list[2][0]

'NewCases'

Остается превратить эту структуру в DataFrame. Для этого сначала превратим ее в словарь из списков, где ключами будут названия колонок.

In [16]:
d = dict()
for i in range(9):
    d[field_list[i][0]] = field_list[i][1:]
# d

А теперь сгружаем этот словарь в функцию pd.DataFrame и он превращается в искомый DataFrame

In [17]:
import pandas as pd 
df = pd.DataFrame(d)
df.head(10)

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical"
0,North America,"55,983,218","+5,168","1,142,080",+394,"44,603,557","+3,379","10,237,581","20,048"
1,Asia,"79,027,071","+50,301","1,165,521",+799,"76,064,985","+54,015","1,796,565","27,178"
2,South America,"38,343,935",+707,"1,168,929",+4,"36,513,911",+483,"661,095","12,393"
3,Europe,"63,757,099","+153,275","1,292,897","+2,652","57,587,352","+93,870","4,876,850","12,972"
4,Africa,"8,558,376",+788,"218,167",+22,"7,895,829","+1,531","444,380","2,347"
5,Oceania,"304,314","+2,647","3,650",+38,"246,889",+482,"53,775",322
6,,721,,15,,706,,0,0
7,World,"245,974,734","+212,886","4,991,259","+3,909","222,913,229","+153,760","18,070,246","75,260"
8,USA,"46,597,003",,"761,856",,"36,476,756",,"9,358,391","13,099"
9,India,"34,231,809",+602,"456,418",,"33,614,434","+7,715","160,957","8,944"

In [18]:
df.head(8)

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical"
0,North America,"55,983,218","+5,168","1,142,080",+394,"44,603,557","+3,379","10,237,581","20,048"
1,Asia,"79,027,071","+50,301","1,165,521",+799,"76,064,985","+54,015","1,796,565","27,178"
2,South America,"38,343,935",+707,"1,168,929",+4,"36,513,911",+483,"661,095","12,393"
3,Europe,"63,757,099","+153,275","1,292,897","+2,652","57,587,352","+93,870","4,876,850","12,972"
4,Africa,"8,558,376",+788,"218,167",+22,"7,895,829","+1,531","444,380","2,347"
5,Oceania,"304,314","+2,647","3,650",+38,"246,889",+482,"53,775",322
6,,721,,15,,706,,0,0
7,World,"245,974,734","+212,886","4,991,259","+3,909","222,913,229","+153,760","18,070,246","75,260"

Для удобства переименуем колонки с составными названиями.

In [19]:
df = df.rename(columns={'Country,Other': 'Country', 'Serious,Critical': 'SeriousCritical'})

In [20]:
df.head(8)

,Country,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,SeriousCritical
0,North America,"55,983,218","+5,168","1,142,080",+394,"44,603,557","+3,379","10,237,581","20,048"
1,Asia,"79,027,071","+50,301","1,165,521",+799,"76,064,985","+54,015","1,796,565","27,178"
2,South America,"38,343,935",+707,"1,168,929",+4,"36,513,911",+483,"661,095","12,393"
3,Europe,"63,757,099","+153,275","1,292,897","+2,652","57,587,352","+93,870","4,876,850","12,972"
4,Africa,"8,558,376",+788,"218,167",+22,"7,895,829","+1,531","444,380","2,347"
5,Oceania,"304,314","+2,647","3,650",+38,"246,889",+482,"53,775",322
6,,721,,15,,706,,0,0
7,World,"245,974,734","+212,886","4,991,259","+3,909","222,913,229","+153,760","18,070,246","75,260"

А теперь сгрузим весь процесс, который мы проделали, в одну функцию. Ее аргумент tag = 0 - информация за сегодняшний день, a tag=1 - информация за вчерашний день.

In [21]:
def stat(tag = 0):
    url = 'https://www.worldometers.info/coronavirus/'
    website = requests.get(url).text
    soup = BeautifulSoup(website, 'lxml')
    table = soup.find_all('table')[tag]
    rows = table.find_all('tr')
    d = dict()
    for i in range(9):
        col = []
        key = rows[0].find_all('th')[i+1].get_text().strip()
        
        for row in rows[1:230]:
            r = row.find_all('td')
            col.append(r[i+1].get_text().strip())
        d[key] = col
    df = pd.DataFrame(d)
    df = df.rename(columns = {'Country,Other':'Country', 'Serious,Critical':'SeriousCritical'})
    return df

In [22]:
stat().head(10)

,Country,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,SeriousCritical
0,North America,"55,983,218","+5,168","1,142,080",+394,"44,603,557","+3,379","10,237,581","20,048"
1,Asia,"79,037,845","+61,075","1,166,268","+1,546","76,073,220","+62,250","1,798,357","27,178"
2,South America,"38,343,935",+707,"1,168,929",+4,"36,513,911",+483,"661,095","12,393"
3,Europe,"63,771,697","+167,873","1,292,959","+2,714","57,587,352","+93,870","4,891,386","12,972"
4,Africa,"8,558,376",+788,"218,167",+22,"7,895,829","+1,531","444,380","2,347"
5,Oceania,"304,314","+2,647","3,650",+38,"246,889",+482,"53,775",322
6,,721,,15,,706,,0,0
7,World,"246,000,106","+238,258","4,992,068","+4,718","222,921,464","+161,995","18,086,574","75,260"
8,USA,"46,597,003",,"761,856",,"36,476,756",,"9,358,391","13,099"
9,India,"34,242,185","+10,978","457,165",+747,"33,615,182","+8,463","169,838","8,944"

In [23]:
list(stat()['Country'][:8])

['North America',
 'Asia',
 'South America',
 'Europe',
 'Africa',
 'Oceania',
 '',
 'World']

В первых 8 строках таблицы в колонке Country лежат регионы + Мир. Одна строка пустая. Уберем ее с помощью спискового включения.

In [24]:
print(*list(i+'\n' for i in list(stat()['Country'][:8]) if i!=''))

North America
 Asia
 South America
 Europe
 Africa
 Oceania
 World

А с 8 по 232 строки лежат названия стран. Выведем ее с помощью спискового включения по 6 стран в линию (для этого вставим символ переноса строки)

In [30]:
x = stat()['Country'][8:230]
', '.join([e+'\n' if i%6 == 5 else e for i,e in enumerate(x)])

'USA, India, Brazil, UK, Russia, Turkey\n, France, Iran, Argentina, Spain, Colombia, Italy\n, Germany, Indonesia, Mexico, Poland, South Africa, Ukraine\n, Philippines, Malaysia, Peru, Netherlands, Iraq, Thailand\n, Czechia, Japan, Canada, Chile, Romania, Bangladesh\n, Belgium, Israel, Pakistan, Sweden, Serbia, Portugal\n, Cuba, Morocco, Kazakhstan, Vietnam, Switzerland, Hungary\n, Jordan, Austria, Nepal, UAE, Greece, Tunisia\n, Georgia, Lebanon, Guatemala, Belarus, Bulgaria, Costa Rica\n, Saudi Arabia, Sri Lanka, Azerbaijan, Ecuador, Bolivia, Myanmar\n, Panama, Slovakia, Paraguay, Croatia, Ireland, Palestine\n, Kuwait, Venezuela, Lithuania, Uruguay, Denmark, Dominican Republic\n, Honduras, Ethiopia, S. Korea, Libya, Mongolia, Moldova\n, Slovenia, Egypt, Oman, Armenia, Bahrain, Kenya\n, Bosnia and Herzegovina, Qatar, Latvia, Nigeria, Zambia, Algeria\n, Norway, North Macedonia, Estonia, Botswana, Uzbekistan, Singapore\n, Albania, Kyrgyzstan, Australia, Finland, Afghanistan, Mozambique\n, Montenegro, Zimbabwe, Ghana, Namibia, Uganda, Cyprus\n, Cambodia, El Salvador, Cameroon, Rwanda, Jamaica, Maldives\n, Luxembourg, Senegal, Angola, Malawi, Ivory Coast, DRC\n, Trinidad and Tobago, Réunion, Guadeloupe, Fiji, Suriname, Eswatini\n, French Guiana, Madagascar, Martinique, Syria, Sudan, French Polynesia\n, Laos, Cabo Verde, Malta, Mauritania, Guyana, Gabon\n, Guinea, Papua New Guinea, Belize, Tanzania, Togo, Benin\n, Haiti, Bahamas, Seychelles, Lesotho, Somalia, Mayotte\n, Burundi, Timor-Leste, Mauritius, Tajikistan, Curaçao, Congo\n, Barbados, Nicaragua, Taiwan, Mali, Aruba, Andorra\n, Burkina Faso, Djibouti, Iceland, Equatorial Guinea, Channel Islands, Brunei\n, Saint Lucia, Hong Kong, South Sudan, CAR, New Caledonia, Gambia\n, Yemen, Isle of Man, Eritrea, Sierra Leone, Niger, Guinea-Bissau\n, New Zealand, Gibraltar, Grenada, Liberia, Bermuda, San Marino\n, Chad, St. Vincent Grenadines, Dominica, Sint Maarten, Comoros, Antigua and Barbuda\n, Saint Martin, Sao Tome and Principe, Liechtenstein, Monaco, Turks and Caicos, British Virgin Islands\n, Saint Kitts and Nevis, Bhutan, Caribbean Netherlands, Faeroe Islands, St. Barth, Cayman Islands\n, Anguilla, Greenland, Diamond Princess, Wallis and Futuna, Macao, Falkland Islands\n, Montserrat, Saint Pierre Miquelon, Vatican City, Solomon Islands, Western Sahara, MS Zaandam\n, Palau, Vanuatu, Marshall Islands, Samoa, Saint Helena'

In [31]:
x = stat()['Country'][8:232]
import re
# print(x)
print(', '.join([e+'\n' if i%6 == 5 else e for i,e in enumerate(x)]).replace('\n,',',\n'))

USA, India, Brazil, UK, Russia, Turkey,
 France, Iran, Argentina, Spain, Colombia, Italy,
 Germany, Indonesia, Mexico, Poland, South Africa, Ukraine,
 Philippines, Malaysia, Peru, Netherlands, Iraq, Thailand,
 Czechia, Japan, Canada, Chile, Romania, Bangladesh,
 Belgium, Israel, Pakistan, Sweden, Serbia, Portugal,
 Cuba, Morocco, Kazakhstan, Vietnam, Switzerland, Hungary,
 Jordan, Austria, Nepal, UAE, Greece, Tunisia,
 Georgia, Lebanon, Guatemala, Belarus, Bulgaria, Costa Rica,
 Saudi Arabia, Sri Lanka, Azerbaijan, Ecuador, Bolivia, Myanmar,
 Panama, Slovakia, Paraguay, Croatia, Ireland, Palestine,
 Kuwait, Venezuela, Lithuania, Uruguay, Denmark, Dominican Republic,
 Honduras, Ethiopia, S. Korea, Libya, Mongolia, Moldova,
 Slovenia, Egypt, Oman, Armenia, Bahrain, Kenya,
 Bosnia and Herzegovina, Qatar, Latvia, Nigeria, Zambia, Algeria,
 Norway, North Macedonia, Estonia, Botswana, Uzbekistan, Singapore,
 Albania, Kyrgyzstan, Australia, Finland, Afghanistan, Mozambique,
 Montenegro, Zimbabwe, Ghana, Namibia, Uganda, Cyprus,
 Cambodia, El Salvador, Cameroon, Rwanda, Jamaica, Maldives,
 Luxembourg, Senegal, Angola, Malawi, Ivory Coast, DRC,
 Trinidad and Tobago, Réunion, Guadeloupe, Fiji, Suriname, Eswatini,
 French Guiana, Madagascar, Martinique, Syria, Sudan, French Polynesia,
 Laos, Cabo Verde, Malta, Mauritania, Guyana, Gabon,
 Guinea, Papua New Guinea, Belize, Tanzania, Togo, Benin,
 Haiti, Bahamas, Seychelles, Lesotho, Somalia, Mayotte,
 Burundi, Timor-Leste, Mauritius, Tajikistan, Curaçao, Congo,
 Barbados, Nicaragua, Taiwan, Mali, Aruba, Andorra,
 Burkina Faso, Djibouti, Iceland, Equatorial Guinea, Channel Islands, Brunei,
 Saint Lucia, Hong Kong, South Sudan, CAR, New Caledonia, Gambia,
 Yemen, Isle of Man, Eritrea, Sierra Leone, Niger, Guinea-Bissau,
 New Zealand, Gibraltar, Grenada, Liberia, Bermuda, San Marino,
 Chad, St. Vincent Grenadines, Dominica, Sint Maarten, Comoros, Antigua and Barbuda,
 Saint Martin, Sao Tome and Principe, Liechtenstein, Monaco, Turks and Caicos, British Virgin Islands,
 Saint Kitts and Nevis, Bhutan, Caribbean Netherlands, Faeroe Islands, St. Barth, Cayman Islands,
 Anguilla, Greenland, Diamond Princess, Wallis and Futuna, Macao, Falkland Islands,
 Montserrat, Saint Pierre Miquelon, Vatican City, Solomon Islands, Western Sahara, MS Zaandam,
 Palau, Vanuatu, Marshall Islands, Samoa, Saint Helena

Для вывода результатов в текстовом формате воспользуемся библиотекой tabulate (в таком формате мы будем отправлять результаты в telegram'е)

In [49]:
!pip install tabulate

Requirement already satisfied: tabulate in /Users/admin/opt/anaconda3/lib/python3.8/site-packages (0.8.9)

In [50]:
from tabulate import tabulate

Например общее количество случаев заболевания коронавирусом в Великобритании вывести можно так:

In [51]:
df[['Country','TotalCases']][df['Country']=='UK'].reset_index(drop=True)

NameError: name 'df' is not defined

In [35]:
x = df[['Country','TotalCases']][df['Country']=='UK'].reset_index(drop=True)
print(tabulate(x, headers = x.columns, tablefmt="grid"))

+----+-----------+--------------+
|    | Country   | TotalCases   |
+====+===========+==============+
|  0 | UK        | 8,897,149    |
+----+-----------+--------------+

In [36]:
from enum import Enum

class Color(Enum):
    RED = 1
    GREEN = 2
    BLUE = 3

In [37]:
Color.RED